version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: titureco_db
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-sua_senha_segura}
      - POSTGRES_DB=${DB_NAME:-titureco}
    ports:
      - "${DB_PORT:-5434}:5432"
    volumes:
      - titureco_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: titureco_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@titureco.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  titureco_data: