# Conexão com o banco

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:titureco}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:sua_senha_segura}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=${JWT_SECRET:minha-chave-secreta-super-segura-com-pelo-menos-32-chars!}
# Expiração do token: 86400000ms = 24 horas
jwt.expiration-ms=${JWT_EXPIRATION:86400000}